site_name: Godot AdMob Plugin - Poing Studios
theme:
  features:
    - content.tabs.link
    - navigation.instant
    - navigation.indexes 
    - navigation.instant.prefetch
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  name: material
  favicon: assets/icon.ico
  logo: assets/icon.ico
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
markdown_extensions:
  - toc:
      title: On this page
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/YEPvYjSSMk
    - icon: fontawesome/brands/github
      link: https://github.com/Poing-Studios
copyright: |
  &copy; 2023-present <a href="https://github.com/Poing-Studios/godot-admob-plugin"  target="_blank" rel="noopener">Poing Studios</a> | Portions of this page are modifications based on work created and <a href="https://developers.google.com/terms/site-policies"  target="_blank" rel="noopener">shared by Google</a> and used according to terms described in the <a href="https://creativecommons.org/licenses/by/4.0/"  target="_blank" rel="noopener">Creative Commons 4.0 Attribution License</a>.
