site_name: Godot AdMob Plugin - Poing Studios
site_url: https://godotadmob.poingstudios.com/
theme:
  features:
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  name: material
  favicon: icon.ico
  logo: icon.ico
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/YEPvYjSSMk
    - icon: fontawesome/brands/github
      link: https://github.com/Poing-Studios
copyright: |
  &copy; 2023-present <a href="https://github.com/Poing-Studios/godot-admob-plugin"  target="_blank" rel="noopener">Poing Studios</a>