blank_issues_enabled: false
contact_links:
  - name: Issue with AdMob on Android only
    url: https://github.com/Poing-Studios/godot-admob-android
    about: Check the Android plugin repository.
  - name: Issue with AdMob on iOS only
    url: https://github.com/Poing-Studios/godot-admob-ios
    about: Check the iOS plugin repository.
