name: Build Android

on:
  pull_request:
    types: [opened]


jobs:
  generate-build:
    name: Generate Build of Pull Request
    runs-on: "ubuntu-latest"

    steps:
      name: Echo test
      run: echo "test"

