name: Build Pull Request Godot Editor

on:
  [pull_request]

jobs:
  generate-build:
    name: Generate Build of Pull Request
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3
    
    - name: Echo test
      run: echo "test"
    
    - name: Compress .zip
      run: |
        ls
        zip -r compress.zip ./

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      path: compress.zip
        

