name: Build Pull Request Godot Editor

on:
  [pull_request]

jobs:
  generate-build:
    name: Generate Build of Pull Request
    runs-on: "ubuntu-latest"

    steps:
    - uses: actions/checkout@v3
    
    - name: Compress .zip
      run: |
        git archive --format=zip --output compress.zip HEAD

    - name: Uncompress .zip to Artifact
      run: |
        unzip compress.zip -d zip_extract_folder
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: godot-admob-editor-v0.0.0.0
        path: zip_extract_folder/
